### ISSUE TITLE
Polling is bad

### ISSUE THREAD

**Issue by snej** [KrauseFx/WiFiAuth#1]
This code polls once a second for the lifetime of the app. This isn't a good idea for battery life, and polling is almost never a good design. It's not necessary, since SCNetworkReachability has an observer API that lets you get callbacks when something changes.

**Comment by jshier** [comment]
Additionally, Apple's recommended approach is for reachability to only be a *reactive* check. That is, see a network call fail and then check reachability to see if it's due to some known connectivity issue, like Wifi capture. Given the exposure this example has gotten I think it's important for the example to reflect that best practice (in addition to polling being bad).

**Comment by KrauseFx** [comment]
Very true, this repo started out as a joke project and is not designed to be actually used. However it does seem like people think it would be useful, so maybe it's worth finishing? What do you think? 

> This project is just a proof of concept I hacked together in less than an hour.

> However I do believe it might be worth finishing that SDK and make it production ready.

Regarding only checking if any request fails: Is that possible without the use of any kind of swizzling?

**Comment by rwbutler** [comment]
I've written a framework called Connectivity (https://github.com/rwbutler/Connectivity) which solves this problem by using NWPathMonitor on iOS 12 / Reachability to monitor changes in network interface state.

**Comment by KrauseFx** [comment]
Closing this in favor of https://github.com/rwbutler/Connectivity
